### ISSUE TITLE
Slideshow does not run when remembering password option is selected

### ISSUE THREAD

**Issue by Anshil0208** [DMiradakis/Power-BI-Real-Time-Slideshow#1]
Hi

Firstly thank you for developing this. This is a brilliant piece of software.
However, I have picked up an issue where the slideshow does not run after been installed correctly,

I have figured out that when signing into Power BI, after the 'Already have an account screen' you have the 'Pick an account' screen. After typing in your password and clicking 'sign in' you are presented with this screen (pic provided for 'Stay signed in? screen')
![Attached1](https://user-images.githubusercontent.com/62388158/77075683-62971e00-69fb-11ea-9f82-c9e8870b76b4.PNG)

If you click 'No'  and follow the instructions provided the software works perfectly . If you select 'Yes' and follow the instructions provided the slideshow does not start.

I can also add: 
There is an error that I found in the 'Inspect pop-up' option in the icon. 
The was a 404 error and the warning was identifying the 'primer' file in the CCS folder.
**sorry i cannot explain the error very well**

Regards
Anshil

**Comment by Anshil0208** [comment]
Hi 

Any updates on this?

Regards
Anshil

**Comment by DMiradakis** [comment]
Hi @Anshil0208 ,

Thank you so much for the encouragement! Obviously, that ticket on the Power BI community has been open for a while, so I had wondered if anyone would still be paying attention to its responses.

I apologize for my delay in getting back to you! After being sent to work from home, a bolt of lightning broke a **ton** of things in my house, and I've been behind on several things, both work and personal here on GitHub.

Thanks for letting me know about your issue! Let me see if I can reproduce it on my end, and I will get back to you soon. Again, I apologize for my delay in responding to your issue!

**Comment by DMiradakis** [comment]
Hi @Anshil0208 ,

> I can also add:
There is an error that I found in the 'Inspect pop-up' option in the icon.
The was a 404 error and the warning was identifying the 'primer' file in the CCS folder.
sorry i cannot explain the error very well

I was able to see the error you are speaking of regarding the primer css file. See below:

<img width="313" alt="Primer CSS Error" src="https://user-images.githubusercontent.com/53345819/77839353-6cc6c400-7141-11ea-96e4-08c97269be8b.png">

However, I do not see that this should be any kind of error that inhibits the extension from successfully launching. At least, it never has been for me.

In chrome, if you observe the messages from the chrome browser while it is running, it will yield quite a number of errors, but none of them have prevented me from running the extension successfully. Most of the errors I've seen from chrome have to do with the extension forcing the Power BI report to automatically go into full screen mode, as chrome doesn't like this.

Regarding the first portion of your issue, I have not been able to reproduce the issue on my own device. I am not sure why the sign in screens from Microsoft would interfere with the extension's operability. 

If you are able, when you click "Yes" on that sign in screen, please press `<Ctrl + Shift + i>` on your keyboard: this should bring up the chrome developer console. If you can, please provide me a screenshot of what exactly the chrome console is saying after you click the "Play" button on the extension, as that would likely be more telling as to what kind of issue you are experiencing.

Thanks!
