### ISSUE TITLE
Page refreshes when pressing Play, but nothing happens

### ISSUE THREAD

**Issue by magnetarc** [DMiradakis/Power-BI-Real-Time-Slideshow#6]
I changed from 'New Look' back to the old UI.

I open the report in Chrome browser, click the app icon and press 'Play'.

The page refreshes, the report loads again, but nothing happens. It does not enter full-screen mode or rotate through the pages.

Thanks for all of the work on this!

**Comment by DMiradakis** [comment]
@magnetarc 

Would you mind taking a screen recording for me when you try to start the extension?

Specifically, I need to see the log on the Chrome Developer Console.

When you do the screen recording, press `Control + Shift + i` on your keyboard to open the Chrome Developer Console _before_ you begin recording and leave it open the entire time, please.

Then upload that recording here and I can take a look!

Thanks!

**Comment by DMiradakis** [comment]
Closed for inactivity.
