### ISSUE TITLE
The Power BI old UI is not supported anymore

### ISSUE THREAD

**Issue by jpliraa** [DMiradakis/Power-BI-Real-Time-Slideshow#7]
this 11-11-2020 we dont have anymore the old UI for Power BI
 we need your plug in working!!!, thanks you for all

**Comment by DMiradakis** [comment]
@jpliraa 

Oh my goodness, you're right! Yikes... I was afraid this was going to happen soon. I'm actually in the process of finishing up employment at my current job and moving to another, so life is pretty crazy right now. Let me see if I can fix it.

Thanks for bringing this to my attention!

**Comment by jpliraa** [comment]
Thanks to you men, please let me know if you fix this.

**Comment by DMiradakis** [comment]
Closing this issue, as I am addressing it in #2 .
